development:
  adapter: redis
  url: <%= ENV.fetch("redis://127.0.0.1") { "redis://localhost:6379/1" } %>
  channel_prefix: todo_app_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://127.0.0.1") { "redis://localhost:6379/1" } %>
  channel_prefix: todo_app_production
